### ISSUE TITLE
Problem with RegisterHandler and question about functions 

### ISSUE THREAD

**Issue by EncryptSL** [Blad3Mak3r/Slash#11]
Hi, i have question is there way how send response message when commands are blocked in function addCheck.

Thanks for answer.

**Comment by EncryptSL** [comment]
I have another question, i implemented register handler by default from documentation.

```KOTLIN
SlashCommandClient.default("encryptsl.cekuj.net.jmusic.cmds.general")
   .addCheck { ctx ->
       return@addCheck !DiscordUtils.allowedChannels(ctx.channel.id, 
      config.getString("discordbot.server.channels.text.commandChannel").toString())
   }
   .buildWith(bot)
```

But log says 
`12:08:11[INFO] [tv.blademaker.slash.client.DefaultSlashCommandClient] Discovered a total of 0 commands in 81ms.`

I do something bad or something missing ?

**Comment by EncryptSL** [comment]
When class doesn't have any dependency in constructor, framework registering him fine.
```KOTLIN
class Test : BaseSlashCommand("test") {

    @SlashCommand(target = InteractionTarget.ALL)
    suspend fun onTest(ctx: SlashCommandContext) {
        ctx.acknowledge()
        ctx.hook.sendMessage("Hiii every one !").queue()
    }

}
```

But when i add into constructor something dependency, framework not registering him.
```KOTLIN
class Test(something: Else) : BaseSlashCommand("test") {

    @SlashCommand(target = InteractionTarget.ALL)
    suspend fun onTest(ctx: SlashCommandContext) {
        ctx.acknowledge()
        ctx.hook.sendMessage("Hiii every one !").queue()
    }

}
```

Printed error
```
Exception in thread "main" java.lang.NoSuchMethodException: encryptsl.cekuj.net.jmusic.cmds.fun.Test.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
	at tv.blademaker.slash.SlashUtils.discoverSlashCommands(SlashUtils.kt:60)
	at tv.blademaker.slash.client.DefaultSlashCommandClient.<init>(DefaultSlashCommandClient.kt:43)
	at tv.blademaker.slash.client.DefaultSlashCommandClient.<init>(DefaultSlashCommandClient.kt)
	at tv.blademaker.slash.client.DefaultSlashCommandBuilder.build(DefaultSlashCommandBuilder.kt:62)
	at tv.blademaker.slash.client.DefaultSlashCommandBuilder.buildWith(DefaultSlashCommandBuilder.kt:74)
	at encryptsl.cekuj.net.jmusic.JMusicBot.startBot(Main.kt:30)
	at encryptsl.cekuj.net.jmusic.MainKt.main(Main.kt:55)
```

**Comment by EncryptSL** [comment]
Solved by own way.
